// <auto-generated />
namespace Appartments_MVC_Course.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dataanotaionstoapartment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dataanotaionstoapartment));
        
        string IMigrationMetadata.Id
        {
            get { return "202108271244434_data-anotaions-to-apartment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
