// <auto-generated />
namespace Appartments_MVC_Course.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class clea : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clea));
        
        string IMigrationMetadata.Id
        {
            get { return "202109051802563_clea"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
